### PR TITLE
fix for community apps top level domain app

### PR DESCRIPTION
**Pull request by evlo**
I don't know how to test this

### CODE REVIEW

**Comment by johnkennyuk** [comment]
Just PGFork from my repo then ull see its to fix that TLD Traefik.frontend.rule bug so you dont have to manually edit the container manually.

**Comment by johnkennyuk** [comment]
Soz thought was something else.

**Comment by johnkennyuk** [comment]
Isnt this in the Scap folder and not used anymore???

**Comment by evlo** [comment]
> Isnt this in the Scap folder and not used anymore???

Yes pgblitz is current

**Pull request merged**
